version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    ports:
      - "9870:9870"  # Namenode Web UI
      - "9000:9000"  # Namenode RPC port
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CLUSTER_NAME=hadoop-cluster
    ports:
      - "9864:9864"  # Datanode Web UI
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - HOME=/root
      - SPARK_CONF_spark.ui.port=4040  # Force Job UI to use port 4040
      - SPARK_CONF_spark.eventLog.enabled=true
      - SPARK_CONF_spark.eventLog.dir=file:/mnt/spark-logs
    ports:
      - "7077:7077"  # Spark Master RPC port
      - "8080:8080"  # Spark Master Web UI
      - "4040:4040"  # Spark Job Details UI
    volumes:
      - ./consumerJobs:/opt-spark-jobs
      - spark-master-data:/bitnami/spark
      - spark-checkpoints-data:/mnt/spark-checkpoints
      - spark-logs:/mnt/spark-logs
      - spark-state:/mnt/spark-state
      - /tmp/ivy-cache:/tmp/ivy-cache
    depends_on:
      - namenode
    networks:
      - hadoop-network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/root
    ports:
      - "8081:8081"  # Spark Worker 1 Web UI
    volumes:
      - spark-worker1-data:/bitnami/spark
      - spark-checkpoints-data:/mnt/spark-checkpoints
      - spark-logs:/mnt/spark-logs
      - spark-state:/mnt/spark-state
      - /tmp/ivy-cache:/tmp/ivy-cache
    depends_on:
      - spark-master
      - namenode
    networks:
      - hadoop-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/root
    ports:
      - "8082:8081"  # Spark Worker 2 Web UI
    volumes:
      - spark-worker2-data:/bitnami/spark
      - spark-checkpoints-data:/mnt/spark-checkpoints
      - spark-logs:/mnt/spark-logs
      - spark-state:/mnt/spark-state
      - /tmp/ivy-cache:/tmp/ivy-cache
    depends_on:
      - spark-master
      - namenode
    networks:
      - hadoop-network

  spark-history:
    image: bitnami/spark:latest
    container_name: spark-history
    hostname: spark-history
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/mnt/spark-logs
    ports:
      - "18080:18080"  # Spark History Server UI
    volumes:
      - spark-logs:/mnt/spark-logs
    depends_on:
      - spark-master
    networks:
      - hadoop-network

volumes:
  namenode-data:
  datanode-data:
  spark-master-data:
  spark-worker1-data:
  spark-worker2-data:
  spark-checkpoints-data:
  spark-logs:
  spark-state:

networks:
  hadoop-network:
